name: WarnAntiCheat
version: 1.0
main: fr.thet.warn.Main
author: theT76
depend: [ProtocolLib]
commands:
  warndeban:
    description: deban
  log:
    description: log
  warnban:
    description: ban
  ping:
    description: ping
    usage: /ping ou /ping <Joueur>
  warnff:
    description: warnff
    usage: /warnff 
